### ISSUE TITLE
User amazon SDK waiters with robust defaults

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#6177]
Before the aws SDK had a viable wait method (i.e. to wait for resources to become ready), packer implemented its own version of this. See builder/amazon/common/state.go.

We routinely get issues reported that we're not waiting long enough. I've slowly been replacing the homegrown waiters with the SDK waiters, which generally seems to solve the problems. I think we should remove the home grown waiters for good and replace them with the SDK waiters.

There is a BC aspect to consider:

The common/state.go waiters use the env vars `AWS_POLL_DELAY_SECONDS` and `AWS_TIMEOUT_SECONDS` to control how long to wait.

The SDK waiters implement defaults for the above values per resource. For example, the wait for instances to be running looks like this

```
func (c *EC2) WaitUntilInstanceRunningWithContext(ctx aws.Context, input *DescribeInstancesInput, opts ...request.WaiterOption) error {
        w := request.Waiter{
                Name:        "WaitUntilInstanceRunning",
                MaxAttempts: 40,
                Delay:       request.ConstantWaiterDelay(15 * time.Second),
                Acceptors: []request.WaiterAcceptor{
                        {
                                State:   request.SuccessWaiterState,
                                Matcher: request.PathAllWaiterMatch, Argument: "Reservations[].Instances[].State.Name",
                                Expected: "running",
                        },
                        {
                                State:   request.FailureWaiterState,
                                Matcher: request.PathAnyWaiterMatch, Argument: "Reservations[].Instances[].State.Name",
                                Expected: "shutting-down",
                        },
                        {
                                State:   request.FailureWaiterState,
                                Matcher: request.PathAnyWaiterMatch, Argument: "Reservations[].Instances[].State.Name",
                                Expected: "terminated",
                        },
                        {
                                State:   request.FailureWaiterState,
                                Matcher: request.PathAnyWaiterMatch, Argument: "Reservations[].Instances[].State.Name",
                                Expected: "stopping",
                        },
                        {
                                State:    request.RetryWaiterState,
                                Matcher:  request.ErrorWaiterMatch,
                                Expected: "InvalidInstanceID.NotFound",
                        },
                },
                Logger: c.Config.Logger,
                NewRequest: func(opts []request.Option) (*request.Request, error) {
                        var inCpy *DescribeInstancesInput
                        if input != nil {
                                tmp := *input
                                inCpy = &tmp
                        }
                        req, _ := c.DescribeInstancesRequest(inCpy)
                        req.SetContext(ctx)
                        req.ApplyOptions(opts...)
                        return req, nil
                },
        }
        w.ApplyOptions(opts...)

        return w.WaitWithContext(ctx)
}
```

as you can see, it has the delay hardcoded to 15s, and retries set to 40. We do a 5 minute absolute timeout and 2 second delay. 

I believe packer has a different use-case than the SDK defaults. We don't care so much about liveliness, and instead care deeply about the request eventually succeeding. I believe we should use the SDK waiters with default retries set to 10x the SDK default.

We must also allow these to be overridable by the user in case the values are unacceptable. Ideally we could reuse the existing env vars in a way that makes sense, but we may have to come up with an alternate configuration syntax.

### Todo

- [x] get all the waiters replaced with the SDK waiters
- [ ] increase the default retries 10x
- [x] make the defaults overridable by env vars
- [ ] Document the env var behavior on the website

**Comment by stevemac007** [comment]
I like the approach of using the SDK waiters for this solution - any ETA on having `1.3.0` ready?

**Comment by SwampDragons** [comment]
It'll probably be at least a month -- I'm working on implementing the waiters right now in https://github.com/hashicorp/packer/pull/6332 and will hopefully be done with testing today.  I can build you a binary if you'd like to try it out.

**Comment by SwampDragons** [comment]
@mwhooker I'm not sure points 2 and 4 are necessary in the way I've implemented it; I have used Packer's current env vars instead of overriding them with anything, so the default is already set by those env vars (point 2) and it should already be documented because nothing's changed (point 4)

**Comment by SwampDragons** [comment]
@nstreet `disable_stop_instance` just prevents the instance from being stopped when the build has finished running; it doesn't affect timeouts.

**Comment by SwampDragons** [comment]
@nstreet Looking closer at this, you've found a bug unrelated to the timeouts -- the issue here is that the waiter should be located inside an if statement that it's actually outside of. I can fix that for the next release.

**Comment by SwampDragons** [comment]
Okay, final comment @nstreet  -- I looked into this and it turns out it's a flag for a very very specific use case; for that use case it works fine, but it does not do what you want it to do. I've made a PR updating the docs to make them clearer.

**Comment by PCSshell** [comment]
@SwampDragons any chance I could get a build with this fix in it to try out?

**Comment by SwampDragons** [comment]
@PCSshell sure -- what's your host OS?

**Comment by PCSshell** [comment]
@SwampDragons Ubuntu 16.04

**Comment by PCSshell** [comment]
@SwampDragons Apparently I am not doing something correctly. Below are the commands I am running to set the timeout settings. In the log it is telling me that the values to over ride are not set. 

$ export AWS_POLL_DELAY_SECONDS=10
$ export AWS_MAX_ATTEMPTS=300
$ export AWS_TIMEOUT_SECONDS=3000
$ export PACKER_LOG=1
$ packer build 2012R2/Server2012R2.json

==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
2018/07/11 09:12:43 ui: ==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Terminating the source AWS instance...
2018/07/11 09:12:44 packer: 2018/07/11 09:12:44 No AWS timeout and polling overrides have been set. Packer will defalt to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS to your desired values.

$ echo $AWS_MAX_ATTEMPTS
300
$ echo $AWS_POLL_DELAY_SECONDS
10
$ echo $AWS_TIMEOUT_SECONDS
3000

**Comment by SwampDragons** [comment]
Oh weird. And of course I merged before I saw your comment. I'll take a look at this.

**Comment by SwampDragons** [comment]
ugh, found it. I made some last-minute changes to make testing easier, and... broke the functionality.  😅 
[packer.zip](https://github.com/hashicorp/packer/files/2186072/packer.zip)

**Comment by PCSshell** [comment]
I am still seeing the same behavior. The --version number I am seeing now is [INFO] Packer version: 1.3.0-dev

**Comment by SwampDragons** [comment]
The same behavior as the previous build I gave you? I just tested again locally, and I only get the `No AWS timeout and polling overrides have been set` warning if I have not set the environment variables. If I set the environment variables as you have above, I get a different (correct) warning -- `WARNING: AWS_MAX_ATTEMPTS and AWS_TIMEOUT_SECONDS are both set....` etc

I was bouncing back and forth between several issues yesterday so I guess it's possible I built from the wrong commit (I can't test the binary right now since I'm on a darwin machine)... just in case, here's a new build of the master branch.
[packer.zip](https://github.com/hashicorp/packer/files/2189450/packer.zip)

**Comment by PCSshell** [comment]
Looks like it is recognizing the environment variables now, but does not seem to respect what I am entering for them. 
 
export AWS_POLL_DELAY_SECONDS=30
export AWS_MAX_ATTEMPTS=3000
export AWS_TIMEOUT_SECONDS=3000

2018/07/12 13:47:41 ui: ==> amazon-ebs: Automatic instance stop disabled. Please stop instance manually.
==> amazon-ebs: Automatic instance stop disabled. Please stop instance manually.
2018/07/12 13:47:41 ui: ==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
2018/07/12 13:57:38 ui error: ==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
==> amazon-ebs: Terminating the source AWS instance...
2018/07/12 13:57:38 ui: ==> amazon-ebs: Terminating the source AWS instance...
2018/07/12 13:57:38 packer: 2018/07/12 13:57:38 WARNING: AWS_MAX_ATTEMPTS and AWS_TIMEOUT_SECONDS are both set. Packer will be using AWS_MAX_ATTEMPTS and discarding AWS_TIMEOUT_SECONDS. If you have not set AWS_POLL_DELAY_SECONDS, Packer will default to a 2 second poll delay.
2018/07/12 13:58:39 ui: ==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Cleaning up any extra volumes...
2018/07/12 13:58:39 ui: ==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: No volumes to clean up, skipping
2018/07/12 13:58:39 ui: ==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary security group...
2018/07/12 13:58:40 ui: ==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Deleting temporary keypair...
2018/07/12 13:58:40 [INFO] (telemetry) ending amazon-ebs
2018/07/12 13:58:40 ui error: Build 'amazon-ebs' errored: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
Build 'amazon-ebs' errored: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts

**Comment by SwampDragons** [comment]
No problem -- thanks for your patience as I looked into this.

**Comment by WeekendsBull** [comment]
@SwampDragons I have tried both packer v1.3 and v1.2.3 that I wasn't able to get rid of the error saying unexpected state 'failed', wanted target 'available'

[1;32m==> aws: Copying AMI: us-west-2(ami-0a30229bcbd197499)[0m
[1;32m==> aws: Encrypting with KMS Key ID: arn:aws:kms:us-west-2:8xxxxxxxxxxxx:key/be91ec52-a7ed-4b6b-xxxx-d6594f71axxxxx[0m
[1;32m==> aws: Waiting for AMI copy to become ready...[0m
[1;31m==> aws: Error waiting for AMI Copy: unexpected state 'failed', wanted target 'available'[0m
[1;32m==> aws: Deregistering the AMI because cancellation or error...[0m
[1;32m==> aws: Terminating the source AWS instance...[0m
[1;32m==> aws: Cleaning up any extra volumes...[0m
[1;32m==> aws: No volumes to clean up, skipping[0m
[1;32m==> aws: Deleting temporary security group...[0m
[1;32m==> aws: Deleting temporary keypair...[0m
1;31mBuild 'aws' errored: Error waiting for AMI Copy: unexpected state 'failed', wanted target 'available'[0m

==> Some builds didn't complete successfully and had errors:
--> aws: Error waiting for AMI Copy: unexpected state 'failed', wanted target 'available'

==> Builds finished but no artifacts were created.

**Comment by SwampDragons** [comment]
I'll try to look at this today.

**Comment by WeekendsBull** [comment]
@SwampDragons Thanks for your attention and I added some logs at https://github.com/WeekendsBull/packerbuild-error/tree/master/packer_debug

I put both centos and windows 2012r2 build logs with ones working and works failed. I have only provided packer v1.2.3 and would you want me to provide the v1.3.0-dev as well? 

I put an excel file showing what I have installed in each jenkins slave instances but they are almost identical for installed version. 

Here is the copy of centos template I use at https://github.com/WeekendsBull/packerbuild-error/blob/master/centos7build.json (each build name associated with each account).

**Comment by SwampDragons** [comment]
@WeekendsBull I figured this out and responded to you in the mailing list, but I'll leave a note here in case future users run into the same problem.  You need to increase the AWS timeout by setting the environment variables `AWS_POLL_DELAY_SECONDS` and `AWS_MAX_ATTEMPTS`

For example: 

```
export AWS_POLL_DELAY_SECONDS=5
export AWS_MAX_ATTEMPTS=300
packer build example_template.json
```
or simply:
```
AWS_POLL_DELAY_SECONDS=5 AWS_MAX_ATTEMPTS=300 packer build example_template.json
```

**Comment by samof76** [comment]
Using 1.4.2 version of Packer. And still hit issue, in spite of setting `AWS_POLL_DELAY_SECONDS=5 AWS_MAX_ATTEMPTS=300`, while doing a packer build, here is my base.json...

```
{
    "variables": {
        "region": "us-east-1",
        "ssh_username": "ec2-user",
        "instance_type": "t2.micro",
        "vpc_id": "vpc-xxxxx",
        "subnet_id": "subnet-YYYY"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_name": "eks-ami-sample-{{timestamp}}",
            "region": "{{user `region` }}",
            "vpc_id": "{{user `vpc_id`}}",
            "subnet_id": "{{user `subnet_id`}}",
            "instance_type": "{{user `instance_type` }}",
            "ssh_username": "{{user `ssh_username`}}",
            "associate_public_ip_address": false,
            "source_ami_filter": {
                "filters": {
                    "virtualization-type": "hvm",
                    "source": "amazon/amazon-eks-node-1.13-*",
                    "root-device-type": "ebs",
                    "architecture": "x86_64"
                },
                "owners": [
                    "602401143452"
                ],
                "most_recent": true
            }
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "script": "./scripts/touch_it.sh"
        }
    ]
}
```

**Comment by SwampDragons** [comment]
This issue is a year old -- if you're still experiencing problems then please open a new ticket with full steps to reproduce and full debug logs.
